### ISSUE TITLE
нет сообщения об успешной отправки заявки

### ISSUE THREAD

**Issue by sejunctus** [WahaWaher/sendmail-js#1]
Добрый день!
Замечательный плагин! Огромное человеческое спасибо за его создание!
Никак не могу сообразить, как сделать форму обратного звонка.
Т.е. саму форму в модальном окне я сделал, и сообщение уходит, но форма сама не закрывается и нет сообщения об успешной отправки заявки.

**Comment by WahaWaher** [comment]
Добый, пожалуйста! Здесь список доступных событий: http://wahawaher.000webhostapp.com/sendmail-js/#events и чуть ниже пример использования. Используйте "success.sml", если нужно обработать успешную отправку, "serverError.sml" и "ajaxError.sml" - если ошибки. Логика открытия/закрытия модалок пишется в обработчиках этих событий отдельно. Это уже зависит от того, каким образом модальные окна у вас реализованы.

**Comment by WahaWaher** [comment]
``` javascript
$('form').on('success.sml', function(e, instance, form, response) {
    // Успешная отправка...
}).on('ajaxError.sml', function(e, instance, form, response) {
  // Ошибка на стороне клиента...
}).on('serverError.sml', function(e, instance, form, response) {
  // Ошибка на стороне сервера...
}).sendMail({
  // Настройки...
});
```

**Comment by sejunctus** [comment]
Модальное окно вызывается через Fancybox:
<button class="btn callmeback" data-fancybox data-src="#callbackForm">Заказать звонок!</button>

В настройках JS прописал:
// Настройка обратного звонка
var callback = $('#callbackForm');

callback.on('success.sml', function(e, instance, form, response) {
    // Успешная отправка...
}).on('ajaxError.sml', function(e, instance, form, response) {
  // Ошибка на стороне клиента...
}).on('serverError.sml', function(e, instance, form, response) {
  // Ошибка на стороне сервера...
}).sendMail({
  // Настройки...
});
callback.sendMail();

По итогу сама заявка обрабатывается, но ни сообщения, ни автозакрытия формы не происходит

**Comment by sejunctus** [comment]
сорри, я не программист, поэтому сложновато сообразить ((

**Comment by sejunctus** [comment]
сейчас происходит переход на страницу с сообщением, что форма отправлена

**Comment by WahaWaher** [comment]
Для FB3 как-то так:
``` javascript
$('#callbackForm').on('success.sml', function(e, instance, form, response) {
  // Вывести новое окно
  $.fancybox.open('<p>Спасибо! Ваша заявка успешно отправлена!</p>');
  // Закрыть через 1c
  setTimeout(function() {
    $.fancybox.close();
  }, 1000);
}).on('ajaxError.sml', function(e, instance, form, response) {
  // Вывести новое окно
  $.fancybox.open('<p>Ошибка на клиенте при отправке формы!</p>');
}).on('serverError.sml', function(e, instance, form, response) {
  // Вывести новое окно
  $.fancybox.open('<p>Ошибка на сервере при отправке формы!</p>');
}).sendMail({
  // Настройки...
});
```

**Comment by sejunctus** [comment]
не срабатывает все равно. происходит перенаправление на страницу с сообщением об отправке формы: Форма успешно отправлена!
Т.е. не срабатывает именно отправка AJAX-ом получается
