### ISSUE TITLE
разные темы писем, npm-пакет

### ISSUE THREAD

**Issue by karimch21** [WahaWaher/sendmail-js#2]
Здравствуйте, сегодня познакомился с вашим плагином по отправке формы на почту, вещь просто изумительная, спасибо Вам за труд. 

Хотел буквально поинтересоваться, возможно ли указывать к разным формам, разные темы письма? И почему-то письма в яндекс почте сразу залетают в спам, это решаемо? Так же как я понял нет возможности подключить через npm, шо прям жаль(

 Еще новичек в этом славном деле, буду рад помощи)

**Comment by WahaWaher** [comment]
Здравствуйте. Спасибо!
> возможно ли указывать к разным формам, разные темы письма?

1. Можно добавить в формы дополнительный скрытый инпут, например `<input name="form_type" value="..." hidden>`. Подредактировать `mail/sendmail.php` таким образом, чтобы в зависимости от значения $_POST["form_type"] подставлялась нужная тема.
2. Можно просто прокопировать несколько обработчиков для разных форм со своими темами `mail/sendmail_1.php`, `mail/sendmail_2.php`, и т. д. а в настройках плагина (js) каждой формы указать соответствующий путь к обработчику. Пока как-то так.

> И почему-то письма в яндекс почте сразу залетают в спам, это решаемо?

Сложно тут что-то сказать, нужно смотреть в настройки фильтра ЯндексПочты.

> Так же как я понял нет возможности подключить через npm

в ближайшее время постараюсь добавить
