### ISSUE TITLE
А как отследить с какой формы были отправлены данные?

### ISSUE THREAD

**Issue by karimch21** [WahaWaher/sendmail-js#3]
А как отследить с какой формы были отправлены данные? У меня для каждой формы свои попапы(fancybox) и не очень могу сообразить как написать условие,  при котором бы появлялось свое окно у формы об успешной отправке, т.к появляются на странице все имеющиеся модальные окна)
Извиняюсь, если тупой вопрос

**Comment by WahaWaher** [comment]
Изначально распределить и каждой форме назначить свои обработчики на успешную отправку, если об этом речь:
```js
$('.form_1').on('success.sml', function() {
  $.fancybox.open('...');
}).sendMail({ /* опции... */  });
```
```js
$('.form_2').on('success.sml', function() {
  $.fancybox.open('...');
}).sendMail({ /* опции... */  });
```
и т.д.

Или что-то вроде такого, если отличие форм, например, в атрибутах:
```js
$('.form').on('success.sml', function(e, instance, form, response) {
  if ($(form).hasClass('...')) {
    $.fancybox.open('...');
  }
}).sendMail({ /* опции... */  });
```
